- .travis.yml
This pull request implements continuous integration via [Travis CI](https://travis-ci.org).  Currently it tries to build Git Cola and its documentation in Python 2.6, 2.7, 3.3 and 3.4 environment on every push.
Currently running unit tests is designed but not enabled due to Issue #404 .
> Implement continuous integration, fixes #403

- cola/app.py
- share/doc/git-cola/git-cola.rst
Implement #391:  the ability to refresh `git cola` whenever it gains focus.  This functionality is disabled by default, but can be enabled by setting the `cola.refreshonfocus` git config setting to `true`.  It is not enabled by default because it can result in a pause whenever switching to `git cola` from another application (especially noticeable on Windows).
> Implement refresh-on-focus

- cola/widgets/completion.py
The `filter_matches()` function in widgets/completion.py was calling the list `sort()` method with a `cmp` parameter which is not supported in Python 3.  Rework the code to only use a `key` parameter, and make a couple of other tweaks to the code.
> Fix completion code for Python 3

- cola/gitcmds.py
I have set "log.abbrevCommit = true" in my ".gitconfig" file.
In that case the "More..." items in the "Load previous Commit Message" and
"Fixup previous Commit" sub menus wont work.
The reason is the regular expression REV_LIST_REGEX. It expects the SHA1 to be
exactly 40 characters long in the git log output.
Signed-off-by: Wolfgang Ocker <weo@reccoware.de>
> gitcmds: force option "no-abbrev-commit" when running "git log"

- cola/git.py
long is not defined on Python 3 - it's just int
> Fix Python 3 compatibility

- cola/gitcfg.py
In Python 3, the `bytes` `.decode()` method does not work with `bytes`-to-`bytes` codecs like `hex` (raises a `LookupError`).  This could have been fixed using the `codecs.decode()` function, but I chose to use the `binascii.unhexlify()` function instead, as it seemed slightly more explicit.
> gitcfg: fix GitConfig.color() on Python 3

- cola/models/stash.py
If the user has configured the default diff viewer to be a graphical
viwer then the stash viewer would open the external viewer instead
of displaying the diff in cola
> Don't use external diff in the stash viewer

- cola/qtutils.py
- cola/widgets/diff.py
The previous `DiffSyntaxHighlighter` worked adequately, but because it was stateless, it needed a lot of complicated regular expressions to try to match all the possible diff header lines.  It could also be thrown off, if for example a line was removed starting with `'-- '`, the resulting diff line would start with `'--- '`, causing the syntax highlighter to interpret it as a header line instead of a removal.  To address these shortcomings, completely rewrite the syntax highlighter to be stateful. This greatly simplifies the logic and drastically reduces the number of regular expressions that need to be matched.  Because `DiffSyntaxHighlighter` was the only user of `GenericSyntaxHighlighter`, and `GenericSyntaxHighlighter` does not fit the stateful approach, eliminate …
> Rewrite diff syntax highlighter

- cola/widgets/diff.py
Fix two regressions in diff syntax highlighting introduced by PR #466:
* Diffs of unmerged files were being highlighted using the diff header color, because the regular expression for detecting a diff hunk header did not match the diff hunk header for unmerged files.  Update the regular expression to match both normal and unmerged diff hunk headers.
* Diffs of submodules were being highlighted using the diff header color.  Detect submodule diffs and do not apply any syntax highlighting to them.
> Fix syntax highlighting

- cola/models/main.py
- cola/widgets/main.py
When current working repository is empty (eg: just initialised or cloned
an empty repository), it doesn't make sense to rename or delete local
branch.
For checking whether repository is empty or not, local branches is used.
Alternative considered was:
1. Git log/rev-list and check exit code (Fail when there is remote
branches, bot not local branches)
2. Git count-objects (probably has similar issue with above)
Issue: #459
Reported-By: Vdragon
Signed-off-by: Minarto Margoliono <lie.r.min.g@gmail.com>
> Menu: Disable "Branch" menu in empty repositories

- test/helper.py
Hello.
When running tests in clean sandboxed environments (like the ones used in Gentoo distro), i.e. without a global git config, there is usually no `user.name` and `user.email` specified in the system git config. Because of this, recent versions of git will refuse to commit changes. This in turn makes tests fail.
A simple change should be made to update the said git options. The values are the default ones provided by git's own help message:
```
Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
```
> tests: set 'user.name' and 'user.email' options after the repository init

- cola/difftool.py
- cola/widgets/browse.py
- cola/widgets/compare.py
- cola/widgets/dag.py
- cola/widgets/filelist.py
This adds a context menu option for each file when viewing commit(s) in the DAG. It opens the external diff tool for
- one commit selected: \<commit below selected commit> .. \<selected commit>
- more commits selected: \<commit below bottom selected commit> .. \<top selected commit>
I didn't manage to add Ctrl+D shortcut for that because I don't have that much time (got an error "QAction::eventFilter: Ambiguous shortcut overload: Ctrl+D").
Please check carefully since I don't know the code base / style at all.
> dag: add diff tool option

- cola/core.py
There's an additional Popen flag that needs specifying, as per commit.
Fixes #477
> ensure Git subprocess spawns no window on win32

- cola/models/prefs.py
Default history browser fails to start due to backslashes in Windows path. Converting backslashes to slashes beforehand makes it work for all cases.
> fix history browser default value on win32

- cola/widgets/startup.py
The start-up screen's size has always been a pain point with me, because I could not see at a glance which repositories I wanted to look at with git cola. The path names of the repository were always longer than the window itself. Like this:
This PR widens the window to half the screen width/length, and centers the window on the screen:
I have found this modification very useful and wanted to share it. Please consider merging it :), if you don't like how I fixed the small window problem I can change the code to your satisfaction.
> Center the startup dialog on the screen and make it larger

- cola/models/prefs.py
- cola/widgets/prefs.py
- cola/widgets/status.py
Disabled by default as intended in 0ee6b83. Depending on the theme, dimmed background + bold font is more readable, so give users the choice.
> status: allow bold-with-background headers via preferences

- cola/models/dag.py
- cola/widgets/dag.py
- cola/widgets/text.py
Display entered revision in red if the revision does not exist (to indicate an error). This makes it clearer if invalid branch names or commits were entered.
> dag: show invalid revision in red

- README.md
Fedora replaced YUM with DNF package manager.
> Update fedora instructions on README

- cola/guicmds.py
Change wrong import that prevented cola.guicmds.new_repo() from
successfully creating a new repository. This should also fix issue #277.
> guicmds: fix the "new repository" feature

- bin/git-dag
- cola/app.py
- cola/fsmonitor.py
This PR should fix issue #516.  It first of all limits the scope of `.git` dir monitoring in general to only refresh on changes to `index` and `HEAD` (in additional to changes to files under `refs/`).  Then, for `git-dag`, if further ignores changes to `.git/index` as well as the worktree.  As a result, `git-dag` should only refresh on changes to `HEAD` or `.git/refs/`.
I would like some feedback on how `git-dag` actually enables this behavior however.  I added an optional parameter to `application_start()`, `monitor_refs_only`.  That parameter gets passed in turn to `fsmonitor.instance().start()`.  However, I don't know if this the best mechanism for controlling that behavior.
> Fewer dag refreshes

- cola/fsmonitor.py
- share/doc/git-cola/relnotes/v2.6.rst
git_dir() is the worktree's .git path, but it is not necessarily
the path where refs/ objects/ and friends are found.  When using
submodules, for example, .git is a file that contains the path
to the actual git repository.
The fsmonitor registers the git path so that it can notice
changes.  When doing so it ignores ENOTDIR errors to avoid a
race condition, but it also silently ignores the request to
watch the .git-file.
This later causes an exception when asking for the git path:
File "cola/fsmonitor.py", line 207, in refresh
self._git_dir_wd = self._git_dir_wd_map[self._git_dir]
KeyError: u'/home/david/src/git/.git'
Fix the logic by using git_path() when setting up the monitor so
that the real git repository path is used.
Closes #545
Reported-by: Wolfgang Ocker <weo@reccoware.de> …
> fsmonitor: use the resolved git repository path

- .pylintrc
- .travis.yml
- cola/app.py
- cola/fsmonitor.py
- cola/git.py
- cola/gitcfg.py
- cola/models/main.py
- test/git_test.py
Refactor the git module to simplify the code and make it more amenable to testing.
Teach fsmonitor, gitcfg, and app startup to handle bare repositories.
Teach the git discovery code to honor GIT_CEILING_DIRECTORIES.
Add unit tests covering various aspects of repository discovery.
> git: add support for bare repositories and GIT_CEILING_DIRECTORIES

- cola/app.py
- cola/cmds.py
- cola/fsmonitor.py
- cola/models/main.py
- share/doc/git-cola/relnotes/v2.6.rst
Move common functionality into the main model to fix a subtle bug when launching
from a desktop icon, and to simplify responsibility for callers.
Closes #548 
> Read per-repository configuration when launched from a desktop icon

- cola/hotkeys.py
- cola/widgets/main.py
Hi, I didn't see anything about your policy on pull requests but since you have a how-to fork line I thought I might just send it directly.
Using CTRL+L to focus the commit message box came naturally but going back to the status window was not as intuitive. I figured CTRL+K is a good choice since CTRL+L came to me from browser use and CTRL+K is sometimes used for the search box in browsers (e.g. firefox)
If you don't want to merge it that's fine though.
> Add Ctrl+K shortcut to focus status window

- share/doc/git-cola/_themes/sphinx_rtd_theme/footer.html
- share/doc/git-cola/_themes/sphinx_rtd_theme/versions.html
The main Read the Docs site is still at `readthedocs.org`, so switch those links back from `readthedocs.io`.
> Fix main Read the Docs links

- cola/cmds.py
This fixes the case when commit.template is like "~/.gitmessage".
> BUG: Expand user in path when loading commit message from template.

- cola/cmds.py
- cola/models/main.py
- cola/widgets/status.py
- share/doc/git-cola/relnotes.rst
Refresh the diffstat view when filesystem notifications are received.
> status: handle diffstat notifications

- cola/compat.py
- cola/widgets/standard.py
Must pass "bytes" data type to QByteArray in PyQt5.
> fix early crash on python3 + PyQt5

- cola/widgets/commitmsg.py
This feature is typically used in exceptional cases (e.g. commit something that I will not push unchanged), so my usual workflow is to reset the flag immediately after using it. Add a configuration for auto-resetting that flag.
> Allow auto-reset of "Bypass Commit Hooks" setting

- cola/widgets/dag.py
- cola/widgets/main.py
293364b45c4cbf3faff3fd7aba79b474d0abc845 introduced the problem that e.g. the displayed branch isn't updated when opening the DAG window a second time from the menu. I noticed because I switch between Git repositories all the time using bookmarks, and suddenly the DAG tried to show a feature branch that wasn't in the current repo ;)
This change adds an option to update an existing DAG view, which is used when opened from the main widget.
> Update DAG window when shown again

- cola/widgets/standard.py
Rebase win32 fix is commented with regard to its logic. As for creationflags and STARTUPINFO I moved it to the same place. There was no need to put them in random files during the initial fix.
The same behavior occured on both msys2 (Cygwin fork) git and official git apparently built with mingw-w64. Perhaps git has some flaky logic in interactive rebase.
As for widget size changes - I can submit them separately if you wish. Or just merge `FETCH_HEAD^^` 👍
> Rebase win32 fix and window size improvements

- cola/widgets/browse.py
Fixes bug #616
The save button did not prompt to enter a location to save the blob
This change replaces one (presumably) wrong method call with the same
method call that is used when double-clicking a file instead of using
the save button.
> widgets/browse: fix save bug for "Grab File..."

- cola/widgets/remote.py
Even if "Fast Forward Only" was deselected, a branch wouldn't be force-pushed unless the remote branch is selected in the dialog. That's because of the implementation
```
def refspec(src, dst, ffwd, push=False):
if push and src == dst:
spec = src
else:
spec = '%s:%s' % (src, dst)
if not ffwd:
spec = '+' + spec # <-----------
return spec
def refspec_arg(local_branch, remote_branch, ffwd, pull, push):
"""Return the refspec for a fetch or pull command"""
if not pull and local_branch and remote_branch: # <-------------
what = refspec(remote_branch, local_branch, ffwd, push=push)
else:
what = local_branch or remote_branch or None
return what
```
This change therefore requires the remote branch to be selected. I could have changed the implementation, but I think since force-push is so …
> Require remote branch to be specified in Push dialog for non-fast forward mode since implementation only does force-push in that case

- cola/app.py
This change was introduced to fix Homebrew/legacy-homebrew#7462, which describes an installation issue that is specific to Homebrew and not to macOS in general. If Homebrew really needs this workaround, this change should be applied as a local patch instead of forcing /usr/local to be added to sys.path for everyone.
MacPorts has to remove this addition to sys.path, see macports/macports-ports@e215228a4a18d51ae099e63ad1b416757af64150
If the git-cola maintainers insist on this `sys.path` addition and there is no other solution to be found for Homebrew, I am also fine with keeping the local patch in MacPorts, but in my opinion the maintenance overhead should be where problems are introduced.
I could not find responsible maintainers from @Homebrew to specifically mention on this.
This reverts …
> Revert "app: Make homebrew work by default"

- cola/models/prefs.py
- cola/widgets/commitmsg.py
- cola/widgets/prefs.py
The spellcheck setting was stored in checkbox and reseted after program exit.
The setting is now stored via gitcfg and retrieved after program startup.
Also, add another spellcheck checkbox in preferences window.
Motivation: #596 #632 
Signed-off-by: Szymon Judasz szymon.judasz@student.uj.edu.pl
> commitmsg: keep spellcheck selection after exit

- cola/models/dag.py
- cola/widgets/dag.py
Current commit layout algorithm returns bad looking graph in several
sophisticated configurations. Defects could be found near commits
a049169
2462221
of Git Cola graph. The ambiguous edge overlapping may confuse a user.
The new algorithm is free of this defects. No other defects were found in
Git Cola graph too. While overall appearance still could be improved there
are no confusing configuration noticed.
The layout technique description is presented by comments in the code.
> Change DAG  layout technique

- cola/models/dag.py
- cola/widgets/dag.py
The patch series improves DAG laying out algorithm to prevent label overlapping with commits and other labels. It introduces row distribution technique and embeds it into column distribution algorithm.
The difference could be easy seen by adding tags to left branch commits of parallel branches.
First patch fixes incorrect DAG scrolling. If bottom commit generation is zero then it is hidden below bottom edge of the widget. The issue could be reproduced by showing whole the graph.
> Prevent label overlapping in DAG

- cola/widgets/dag.py
A graph configuration is found that is not correctly handled using current way to maintain occupied column set. If all children of a fork commit are merges and they are assigned a column before the commit processing then no one of children will be assigned same column. Also, no one of them will left parent's column because of the condition in the main loop. In other configuration the column is left when a non-fork ancestor at the column merges. But, in current configuration, no child remains on the column. As a result, the column 'leaks'. This causes the graph spreading.
Such configuration is not found in Git-Cola graph. I've found one in Qemu graph. After selected fork the 7-th column leaks.
Investigating the bug I have realized that fixing up the predicate is possible but it will result …
> Simplify column assignment algorithm

- cola/widgets/gitignore.py
- cola/widgets/status.py
Hi,
This is something I missed when I tried to add a custom pattern in my .gitignore. 
It changes the default 'Add to gitignore' action to show a simple dialog where custom pattern can be set. Multiple files can be set using a ';' to separate them.
Screenshot:
> Add gitignore dialog

- cola/widgets/dag.py
Current column allocation algorithm is too straightforward. It results in following issues.
Graph inclines towards one direction. I think symmetric DAG would appear more pretty.
Graph is spread enought after merging of many parallel branches. In such situation new branches may jump far enough from its forks because the fork column is far from 0 column and there is free column near 0.
The patch series targets mostly this issues.
Changing of graph alignment in commit 02818e2 breaks tag label overlapping prevention algorithm. The patch dd164d177294e0c7f1bb94629c48564badf52364 improves the algorithm to be adaptive to current graph alignment.
> Symmetric DAG

- cola/widgets/dag.py
I just faced a DAG window freezing. When a column is allocated after all columns were left, declare_column method falls into infinity loop searching for an occupied column. The situation may occurs during multiroot graph drawing.
> Fix up infinity loop bug while multiroot graph drawing

- cola/widgets/dag.py
Ascending order of generations may be broken during loading of a big graph. This results in repositioning of commit nodes. On the other hand, every edge is created once during commit addition and edge bounding rectangle is defined during the edge creation. This confuses Qt causing it skip edge redrawing.
This patch series introduces edge invalidation and optimizes edge path update.
> Fix up edge disappearing

- cola/widgets/dag.py
I've investigated the issue about KeyError in propagate_frontier. That was 52-th column in may case. Sometimes the error had not appeared. Hence, I guess the error is related to non-determinism of incremental graph loading. All children of currently added nodes are assigned a column. But, some of them might not be reset because they are not added yet. During consequent iteration the algorithm assumes that corresponding column is allocated because it was not reset. This time the error raises.
I suggest to use depth-first traversal of graph during reset. Complexity of the algorithm seems to remain O(N) while this guaranties that all nodes are reset.
I had not got an error during 10 runs. However, it would be nice if you check it at your side.
> Depth-first traversal column reset

- cola/widgets/commitmsg.py
If a merge conflict resolution results in nothing being staged, git-cola doesn't allow committing. But a commit needs to be done to complete the merge.
> allow commit with nothing staged if it is needed to finish merge

- cola/models/main.py
- cola/widgets/remote.py
> Add prune option for fetch

- cola/git.py
should return an absolute path if a relative path is in the .git file of a submodule
> return abspath in read_git_file for submodule

- cola/models/main.py
After adding a submodule, its folder will be shown in untracked. However, git add folder/ will add all files in folder in windows and git add folder will only add the submodule's folder. Or one can do this check in status.py, but I think in gui, adding a folder will never happen because it always shows untracked or modified files one by one
> for submodule's folder,if stage with /,stage all files in it in windows

- cola/widgets/editremotes.py
In commit 98303c5 AddRemoteWidget's `name` attribute has been renamed to
`remote_name`, however RemoteEditor.add() isn't updated accordingly,
causing add new remote operation failed silently.  This commit completes
the attribute name change.
Signed-off-by: Ｖ字龍 <Vdragon.Taiwan@gmail.com>
> editremotes: update referenced attribute, fixes #684

- cola/widgets/dag.py
- test/short_branch_overlapping.sh
Tag overlapping prevention algorithm can cause an overlapping with terminated branch.
The reproducing script with explanation is added by this patch series. The scripts build the graph represented below.
After the bug is fixed the graph becomes as represented below.
Another kind of overlapping is seen (edges of branches b6 and b7). But it is up to other bug that is being investigated.
> Prevent overlapping with terminated branch

- cola/widgets/createtag.py
Add completer to tag_name in createtag.py so user is informed about
existing tags.
Reported-by: @Vdragon #691
Signed-off-by: Szymon Judasz szymon.judasz@student.uj.edu.pl
> createtag: autocompletition on tag_name field

- cola/models/prefs.py
- cola/widgets/prefs.py
- cola/widgets/text.py
- share/doc/git-cola/git-cola.rst
Add option in models/prefs.py and widgets/prefs.py to override tab with spaces
Override keyPressEvent in TextEdit with new behaviour (intercept tab key when
option is checked and post new keypress and keyrelease events with spaces).
Reported-by: @conz27 #660
Signed-off-by: Szymon Judasz szymon.judasz@student.uj.edu.pl
> text: add option to change pressed tab into spaces

- cola/widgets/branch.py
- cola/widgets/main.py
Hi!
This is a simple filter that hightlight the branches containing the text on it.
Signed-off-by: javierrodriguezcuevas <javierrodriguezcuevas@gmail.com>
> branch: add filter widget

- cola/qtutils.py
- cola/widgets/action.py
Reacting to the pushed event makes the interface behave unlike any other
GUI out there. Restore the normal clicked behaviour. Fix #604 using a
bounce function.
This reverts d9a3f3f8f84d15723dd10ded2adeb6d9ffeb1fcd while still
fixing #604
> qtutils: use the proper clicked signal instead of pressed

- cola/widgets/status.py
If no file selected, hide actions that only work if at least one path is passed to them.
> status: only show file-related context menu actions if a file is selected

- cola/git.py
git-cola freezes when `git` is not found in `PATH`. The cause is a deadlock on `INDEX_LOCK`. The mutex is not released after an exception. I faced with this under Windows but the problem is probably actual for all the OSes.
This patch request elimenates the deadlock and also fixes checking for git existence under Windows.
> Freezing without git

- cola/qtutils.py
- cola/utils.py
Disables annoying behaviour when RMB is pressed to show menu, cursor is
moved accidentally few pixels onto newly created menu and released
causing to execute menu action. Achieved by introducing short period of
ignoring mouse release events.
Fixes #643
> widgets: disable annoying context menu behaviour

- po/fr.po
Line should have read « Tirer » ("Pull") instead of « Pousser » ("Pull").
Signed-off-by: Louis Rousseau <louisrousseau@gmail.com>
> localization: Fix French push-pull mixup 

- cola/widgets/filelist.py
The option "Launch Editor" displays the text "Launch Diff Tool".
> Fixed label in filelist widget

- cola/widgets/status.py
Corresponding interface:
I have no idea what the `r` character before the single quote is so I leave it intact, please review.
Signed-off-by: Ｖ字龍 <Vdragon.Taiwan@gmail.com>
> status: Don't mark custom copy action value template string as translatable

- cola/cmds.py
The revert unstaged/uncommited edits message clarification.
The original message was not specific about the reverted files, it was not clear whether it's related to selected file(s) or all changed files.
> Revert unstaged/uncommited edits message

- cola/widgets/startup.py
Currently, after cloning a remote repository within the startup window, an `AttributeError: 'Clone' object has no attribute 'ok'` is thrown and the main window is not opening despite successful result.
This patch changes the conditional check to use the `status` property of `Clone` object instead, to fix this.
> startup: fix missing GUI after cloning a repo

- cola/cmds.py
- cola/guicmds.py
- cola/widgets/clone.py
Extend the clone dialog with additional options possible to select. Those options are initializing required submodules with `--recurse-submodules` and reducing commit history to minimum with `--depth 1`.
This resolves #535.
> Extend the clone dialog

- cola/gitcmds.py
If the user specified a different preference, Git-Cola should honor that
and not use the patience algorithm. If no preference is set, Git-Cola
continues defaulting to the patience algorithm.
Fixes #799
Signed-off-by: Kai Krakow <kai@kaishome.de>
> gitcmds: Don't force patience diff algorithm

- cola/widgets/log.py
The previous format displayed a weird date/time when the active locale
didn't have AM/PM (%p): `10:45  57s 2018-04-12`.
> app: change date/time format in log widget

- po/de.po
- test/i18n_test.py
This improves the German translation by bringing it more in-line with
the wording of the official Git Book and removes some ambiguous
translations. It also replaces most occurrences of Git technical terms
with their English original as the German Git Book does. It should be
more clear now what each action really does.
Further work will follow while I'm using the software but the current
stage should be suitable for merge.
The po file was edited with poedit2 so it may result in more diff lines
than a hand-crafted edit. But at least the file now follows poedit2
format.
Signed-off-by: Kai Krakow <kai@kaishome.de>
> Improve German translation

- cola/widgets/completion.py
I faced a buggy behaviour of `GitDialog` (`GitBranchDialog` in particular).
Sequence to reproduce:
1. press `Alt` and `B`
2. release them after the branch dialog showed
3. press some buttons to input a branch name (for instance, `m`, `a`, `s`, `t`, `e`, `r`)
Expected result: the branch name (`master`) was entered.
Actual result: only first character (`m`) was entered.
Environment: Ubuntu Linux 16.04 amd64, GNOME Flashback desktop env., Compiz window mgr.
This bug is not appears if the branch dialog is opened using menu.
Adding a short delay before auto completion popup showing fixes it.
> Fixup GitDialog input focus

- cola/hotkeys.py
- cola/widgets/main.py
git's rebase feature is frequently used while preparing commits for publication.
Currently, rebase controls are placed deep in the menu.
Assigning hotkeys for them would be very handy.
I propose to use same hotkeys (`Alt` + `R`) for both Start and Continue
because they are never active simultaneously.
> Add Alt+R hotkeys for both rebase Start and Continue

- cola/cmds.py
The following error occurred when selecting Commit > Unstage From Commit from the menu:
```
UnstageSelected exception:
NameError("global name 'model' is not defined",)
Traceback (most recent call last):
File "/share/git-cola/lib/cola/cmds.py", line 2365, in do
return cmd.do()
File "/share/git-cola/lib/cola/cmds.py", line 2217, in do
self.unstage_paths()
File "/share/git-cola/lib/cola/cmds.py", line 2223, in unstage_paths
return unstage_all(model)
NameError: global name 'model' is not defined
```
This appears to be a misnamed name reference, this patch renames it with the surrounding references.
Signed-off-by: Ｖ字龍 <Vdragon.Taiwan@gmail.com>
> cmds: Fix NameError in Commit > Unstage From Commit

- cola/widgets/status.py
When moving selection up/down with keyboard in a long file list the
selected item goes out of view and there's no way to tell which file the
current diff corresponds to.
This change ensures that latest selected item is always visible.
The horizontal scrolling is preserved as it was implemented before.
See also issue #494 and pull request #178 for related discussion.
Signed-off-by: Petr Gladkikh <petrglad@gmail.com>
> status: Scroll current item into view when selection changes

- cola/widgets/diff.py
In commit 649de5bb248c3a33e6778c44f75ab4457e13508c the diff viewer was refactored to be able to display images diffs.  As a result of that change the `parent` passed to the `Options` object is now a `Viewer` rather than a `DiffEditor`.  In the `Options.update_options()` method, it calls the `update_options()` method of the `parent` provided when it was constructed.  However, unlike `DiffEditor`, `Viewer` did not have an `update_options()` method, which would cause an exception when `Options.update_options()` was executed.
To address this add an `update_options()` method to `Viewer` which delegates to the `update_options()` method of the contained `DiffEditor`.
Fixes: #833
> diff: fix changing diff viewer options

- cola/gitcfg.py
In order to handle string values which happen to be a valid int (for
example a hex string '030303'), establish some type of quoting
mechanism.  In this case, single quotes at the beginning and end of the
value will be stripped and the value itself will be interpreted as a
string rather than an int, as was previously.
Signed-off-by: Uri Okrent <uokrent@gmail.com>
> cola.gitcfg: handle single-quoted strings in git config

- cola/cmds.py
The first line of the body in the "Rename Remote" dialog is redundant and
unnecessary, this patch removes the message and changes the interaction
to a question.
The new interaction choice might not be sane though, please review.
Fixes #838.
Refer-to: Redundant query message · Issue #838 · git-cola/git-cola <https://github.com/git-cola/git-cola/issues/838>
Signed-off-by: 林博仁 <Buo.Ren.Lin@gmail.com>
> cmds: Remove redundant query message

- Makefile
The build will break when either DESTDIR or prefix contains spaces, this patch wraps the expansion with quotes to avoid the word separations.
> Makefile: Avoid word separation in parameter expansion

- contrib/win32/pynsist-preamble.py
__os__ is used 5 times but is never imported.
> import os in pynsist-preamble.py

- cola/actions.py
- cola/cmds.py
- cola/models/selection.py
- cola/widgets/diff.py
> Launch editor at line from diff view

- cola/app.py
- cola/cmds.py
- cola/core.py
- cola/gitcfg.py
- cola/widgets/browse.py
- cola/widgets/common.py
- cola/widgets/status.py
On Windows, Launch Terminal action was not avaliable. Instead we can
just run git bash. This change add following behaviour: Try to find git
bash (sh.exe) executable in typical locations and if one is found, add
Launch Terminal action just like on Unix platforms.
Possible future improvements: better way to find git bash location and
ability to customize it in preferences.
Signed-off-by: Mariusz Jaskółka <mar.jaskolka@gmail.com>
> windows: run git bash when open terminal action is invoked on windows

- cola/core.py
This small change fix running terminal (sh.exe) on windows when
_win32_find_exe('start') returns wrong path (C:\Program
Files\Git\usr\bin\start on my computer).
Signed-off-by: Mariusz Jaskółka <mar.jaskolka@gmail.com>
> windows: remove unnecessary exe searching when executing/forking in shell

- cola/cmds.py
- cola/gitcmds.py
- cola/icons.py
- cola/models/main.py
- cola/widgets/branch.py
- cola/widgets/main.py
- share/git-cola/icons/a-z-order.svg
- share/git-cola/icons/dark/a-z-order.svg
- share/git-cola/icons/dark/last-first-order.svg
- share/git-cola/icons/last-first-order.svg
Currently, branches are alphabet ordered.
But it's also handy to sort them by committer time.
So, recently edited branches are to the top of the list.
This patch series adds a toggle button to branch widget, allowing a user to select desired order.
Current order is also preserved in the state.
> Branch sort order based on committer time

- po/de.po
This fixes some translations were the git command in the
original version differ from the german translation. This
could be confusing to the users.
>  Fix some translations where the git command was wrong

- cola/themes.py
* Prevent drawing frame inside frame when Diff view was shown
* Add padding to the DockTitleBarWidget to fix ugly zero-pixels padding
between frame and label
* Make focus color less distractive on dark themes
Signed-off-by: Mariusz Jaskółka <mar.jaskolka@gmail.com>
> themes: improvements

- cola/i18n.py
This is not a complete solution. But it can solve the errors in `cola/i18n.py`. After this is solved, I get new errors from `cola/decorators.py`:
```
Traceback (most recent call last):
File "./bin/git-cola", line 54, in <module>
sys.exit(main())
File "/home/guo/git/other/git-cola/cola/main.py", line 28, in main
return args.func(args)
File "/home/guo/git/other/git-cola/cola/main.py", line 300, in cmd_cola
view = MainView(context, settings=args.settings)
File "/home/guo/git/other/git-cola/cola/widgets/main.py", line 143, in __init__
editor = commitmsg.CommitMessageEditor(context, self)
File "/home/guo/git/other/git-cola/cola/widgets/commitmsg.py", line 104, in __init__
icon=icons.configure(), tooltip=N_('Actions...'))
File "/home/guo/git/other/git-cola/cola/icons.py", line 177, in configure …
```
> Python2 unicode support with translations

- cola/models/stash.py
- cola/widgets/stash.py
Signed-off-by: xhl <xieofxie@126.com>
> stash: add author date to tool tip

- cola/models/prefs.py
- cola/widgets/completion.py
- cola/widgets/prefs.py
In case project has many files.
I'm sorry that I'm working on Windows so I didn't run make check and make pot.
> dag: add set_revtext_gather_paths

- cola/fsmonitor.py
If file system change monitoring is disabled due to reaching the inotify
watch limit, don't display the message indicating that change monitoring
is enabled after displaying the message indicating that it is disabled.
Signed-off-by: Daniel Harding <dharding@living180.net>
> fsmonitor: don't display conflicting messages

- cola/widgets/main.py
The current repo was showing up in the "Open Recent" menu, which serves
no purpose.
Now the current repo is not shown, with the current repo determined from
the path.
Closes #983
Signed-off-by: Tim Brown <stimut@gmail.com>
> main: hide current repo from "Open Recent" menu

- cola/cmds.py
- cola/models/main.py
- cola/widgets/bookmarks.py
Currently, the recent repo list is only updated when the application is
exited, due to the list being stored in the settings, which are saved on
exit. As well as newly opened repos not showing on the recent list, it
means that if you start on repo A, open repo B, then open repo C, and
finally exit, repo B will not have been added to the recent list.
With this change, when a repo is opened it will be added to the recent
list immediately, and will therefore show in the recent repo list in the
menu. In addition to that, a signal was created for the changing of the
worktree, so that the bookmarks widget for the recent repo list can be
updated.
Closes #937
Signed-off-by: Tim Brown stimut@gmail.com
> recent: update recent repo list when opening repo

- cola/widgets/editremotes.py
Previously after added a new remote, we would either reselect the
previously selected remote, or select the first remote in the list.
Since newly added remotes get added to the end of the list, the new
remote was therefore never selected.
This change makes the newly added remote selected in the list.
Closes #875
Signed-off-by: Tim Brown stimut@gmail.com
> editremotes: select newly added remote

- cola/widgets/bookmarks.py
Adds the Delete option to the context menu of Favorites and Recent,
bringing them inline with Branches.
Signed-off-by: Tim Brown stimut@gmail.com
> bookmarks: add a delete option to the right-click menu

- cola/cmds.py
- cola/widgets/gitignore.py
- cola/widgets/status.py
Allow to add files to the local .git/info/exclude
- Rename status widget entry to `Ignore...`
- Add a radio choice between committed .gitignore and local exclusion file
Signed-off-by: Benjamin Somers <benjamin.somers@telecom-bretagne.eu>
> widgets: #1000 allow adding to local exclusions

- cola/core.py
Python3.8 started complaining loudly when trying to open a stream in binary mode but with line buffering enabled.
So we should only try to set `bufsize` to `1` when we enable `text` or `universal_newlines` mode.
see https://docs.python.org/3/library/subprocess.html#subprocess.Popen under bufsize
> Only use line buffering in text mode when calling Popen

- cola/widgets/main.py
- cola/widgets/standard.py
Allow the user to reset the default layout for the main window.
- Add an entry in the main menu;
- Store the default layout at initialization and restore it when asked.
Closes #994
Signed-off-by: Benjamin Somers <benjamin.somers@telecom-bretagne.eu>
> widgets: Add menu item to reset main window layout

- cola/cmds.py
- cola/models/prefs.py
- cola/widgets/prefs.py
- share/doc/git-cola/git-cola.rst
- Add cola.commit.autotemplate constant in preferences
- Add checkbox in both "All repositories" and "Current repository"
- Load commit template if needed when opening new repository
Closes #735
> prefs: option to automatically load template commit

- cola/settings.py
The Recent repository count setting did not work as expected due to an off-by-one error.
If the setting was set to 4 for instance, then git-cola would keep track of the last 3 repositories (meaning the settings file would have the information on 3 repositories, one of which is the currently opened repository). This was because a nonstrict inequality was used instead of a strict inequality during a check.
With this fix, the settings file correctly now correctly keeps track of the last 4 repositories.
Signed-off-by: Victor Gambier victor.gambier@imt-atlantique.net
> settings: fix issue with Recent repository count

- cola/cmds.py
- cola/core.py
Apparently, Qt's text renderer is pretty slow when text includes
unprintable characters (code points below 32), or many different code
points, or if code points are not part of any fonts. This is possibly
due to font selection fallback handling or so.
Selecting an untracked binary file  can make the git-cola GUI
unresponsive for up to 1 or 2 seconds or so, even if the file size is
well below the default read limit of 2 KB.
Fix this by accepting printable ASCII characters only. string.decode()
using the "ascii" encoding allows unprintable code points below 32, so
filter them manually.
Signed-off-by: wm4 <wm4@nowhere>
> cmds: speed up showing binary untracked files

- share/git-cola/bin/git-xbase
Enhances interactive rebase, by adding the file listing for the selected commit in the bottom pane to make viewing the diff filterable by the selected file if required.
> feat: add file list to interactive rebase

- contrib/win32/pynsist-preamble.py
Since a fix (https://github.com/takluyver/pynsist/pull/149 ) you made in Pynsist a couple of years ago, this workaround is no longer needed.
I suspect you also don't need to add `pythondir` to `PATH` any more - the command launchers do this already, and when launching from a shortcut that's the exe directory, which I think should achieve the same thing. But I haven't checked this carefully, so I'm not touching it at the moment.
> Remove workaround no longer needed in pynsist preamble

- cola/widgets/dag.py
Just starting editing on Git Cola since it is a piece of software I use a lot, but thought I'd start with an easy fix. 
The [setWidth](https://doc.qt.io/qt-5/qpen.html#setWidth) for a QPen takes an integer width (in pixels). Passing in a float produces a warning when running the tests (that the implicit conversion may break later).
> Use integer width for setting pen width

- cola/widgets/remote.py
- test/gitcmds_test.py
If a remote.pushDefault is set then use that, rather than origin.
Fixes #1078
I would appreciate some advice on how/where to write a unit test for this new function.
> Use remote.pushDefault if default branch is set

- Makefile
- setup.py
The latest AppStream standard changed its directory name to support not only apps but also libs, etc.
> Change /usr/share/appdata to /usr/share/metainfo

- cola/widgets/startup.py
+ Use an icon layout instead of the original text list. This reduces visual clutter from repeated path suffixes. The (minor) trade-off is that two repos with the same name will look the same.
+ Remove the sorting by path that StartupDialog performed. This lets the settings manage the sorting, and its behaviour seems more intuitive.
+ Bookmarks go first.
+ Recent repos go in reverse chronological order. This will visually separate same-name repos over time.
+ Add path tooltips to bookmarks
When I first started using Git Cola, the startup page felt a bit cluttered to me, so I finally decided to see if I could polish it.
Before:
After:
> Replace startup dialog's bookmark list with icons instead of text list

- cola/app.py
- cola/widgets/standard.py
- cola/widgets/startup.py
Most errors from opening repositories in the startup dialog just silently fail.
This pull request adds messages for:
* Opening a folder that isn't a git repo, offering to create one for the user
* Failing to open a git repo
* Opening a bookmark that no longer exists, offering to remove it from the list
1. Create an empty folder, then open it in the Startup dialog. Click "Create" to init a new repository and open it. 
2. Manually remove your read access to the repo's `.git`. Try to open it from the startup dialog again.
3. Manually delete the repository, then try to open it from the Startup dialog.
> Add better error responses from opening repositories in the startup dialog

- cola/widgets/startup.py
This does not affect the bookmark view if list mode is the user's startup preference.
> Fix Startup bookmark view not showing folders' short paths on launch

- setup.py
There is a small typo in setup.py.
Should read `distutils` rather than `distuils`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, distuils -> distutils

- README.md
- cola/__main__.py
I took the easiest route (for me, on Windows) to get cola to run from a git checkout.
python3.9 -m venv .venv
.\.venv\scripts\activate
pip install .
pip install pyqt5
Then, I lacked an easy to find way to launch cola.
This offers such a way.  It allows to do:
python -m cola
> Allow cola to be started as a module

- cola/gitcfg.py
- cola/version.py
Add `--includes` option only when reading user config.
From [`git config` doc](https://git-scm.com/docs/git-config#Documentation/git-config.txt---no-includes):
--[no-]includes
Respect include.* directives in config files when looking up values.
Defaults to off when a specific file is given (e.g., using --file,
--global, etc) and on when searching all config files.
Fix #1136
> add `--includes` when reading user git config

- cola/cmds.py
Currently the executable `git-cola-sequence-editor` is called always using python. However, some distros need to have this executable replaced with a wrapping script in order to inject the right environment variables. The wrapping script is a bash script and thus failed to be executed using Python. See https://github.com/NixOS/nixpkgs/issues/126131
For such cases it helps to run the executable as-is without explicitly calling Python.
I'm not sure whether this is wanted behavior in general, but this PR attempts to do this for `git-cola-sequence-editor`.
> call git-cola-sequence-editor without python

- cola/cmds.py
- cola/gitcmds.py
- cola/widgets/diff.py
Currently an untracked file needs to be staged first and then unwanted lines must be unstaged. This change will allow "Stage selected line" and "Revert selected lines..." to be used on untracked file.
The logic will be as followed:
When the user select "Stage selected line" on an untracked file, these selected line will be added to staging, and the rest of file will then be listed under modified. When the user select "Revert selected lines.." on an untracked file, those line will be deleted from the file
To generate the diff of the new file, dev null is used. os.devnull is used instead of hard-coding '/dev/null/'. This will ensure it will works in windows environment, where 'nul' is needed instead of '/dev/null'
The downside of using this approach is the return code. git diff will return …
> Diff: Allow partial stage/revert for untracked file

- test/gitops_test.py
If git is configured to sign commits, the signature will be shown by git log,
thus breaking this test. The --no-show-signature parameter avoids printing
the signature.
> Fix test for signed commits

- cola/gitcmds.py
When there is no commit in the repo, there is no HEAD revision. Therefore the diff command returns an error (fatal: bad revision 'head'), and git-cola then use empty text as the diff fallback.
To fix the issue, the diff_helper is updated to check if `ref` exists, and if `ref` doesn't exist, we drop it and not pass it to the git diff. The check is done through the `rev_parse` wrapper in `gitcmds`, which will simply return back `ref`, when it is not in git.
When viewing the diff of a staged file in a commit-less repo, the ref would be 'HEAD'. Dropping 'HEAD' from parameter will make git compare the staged file against file in the working directory.
Issue: #1110
Reported-By: kyanres
Signed-off-by: mmargoliono
> Diff: Fixed staged file diff in a commit-less repo

- share/doc/git-cola/git-cola.rst
(Removing backticks around the "grep" because the other instance in this file doesn't have that either, and for the "diff" view they'd be out of place, and having them different here would look odd.)
> doc: note editor-awareness in diff screen, too

- cola/widgets/about.py
Passing floats to setWidth() is not supported. It worked by accident
in older versions of PyQt.
This is a follow-up commit to 1b10542ec32c1ce798257a758975c564ff9ba893.
> about: use setWidth(int)

- cola/app.py
- cola/widgets/browse.py
- cola/widgets/main.py
- cola/widgets/standard.py
Track open file browser windows via a new `ApplicationContext.browser_windows` attribute.  The context was chosen due to the fact that file browser windows can be opened from the toolbar, and toolbar commands only have access to the context.  In `MainView.closeEvent()`, close any open file browser windows to prevent them from keeping the application open when the user quits.
This change also ensures that there is a reachable reference to the `Browser` object to ensure that it isn't subject to inadvertent garbage collection.
> Keep track of file browser windows

- cola/app.py
- cola/models/browse.py
- cola/qtutils.py
- cola/widgets/branch.py
- cola/widgets/clone.py
- cola/widgets/diff.py
- cola/widgets/grep.py
- cola/widgets/main.py
- cola/widgets/remote.py
- cola/widgets/standard.py
- cola/widgets/startup.py
Currently, when a `Channel` for a `Task` is created, the `Channel` is given a parent.  If for some reason that parent gets deleted from the main thread while the task is running, the `Channel` will also be deleted at the C++ level, though it will still exist at the Python level.  Then once the task has completed and `Task.run()` tries to emit the .result signal on the `Channel,` a `RuntimeError` with the message `"wrapped C/C++ object of type Channel has been deleted"` will be raised.
Although this is unlikely to happen in practice it still represents a potential race condition that is better avoided.  This commit addresses the issue by no longer passing a parent when creating the `Channel` in `Task.__init__()`, instead relying on Python's garbage collection to clean up the `Channel` when …
> No longer pass a parent to Channel in Task.__init__()

- cola/models/browse.py
- cola/widgets/browse.py
Processing the results of `GitRepoInfoTask` is currently quite convoluted, involving posting a custom event type to the `RepoTreeView`, which then processes the event by looking up the model and updating it accordingly.
Simplify by just moving the `.apply_data()` method from `RepoTreeView` to `GitRepoModel` and connecting it to the task directly.
> Simplify GitRepoInfoTask processing

- README.md
- pynsist.cfg
Remove the Visual Studio C++ 2015 DLLs from the pynsist
exclusion list so that we can import Qt modules on Windows
machines that do not have these DLLs installed.
Closes #1196
Closes #1094
> windows: do not exclude vcruntime140.dll

- .github/workflows/main.yml
- Makefile
- extras/__init__.py
- extras/build_util.py
- pynsist.cfg
- requirements/requirements-dev.txt
The setuptools in Ubuntu 20.04 is too old. Activate a newer
one using a Python virtualenv.
> github/workflows: use a virtualenv to get a newer setuptools

- cola/widgets/standard.py
References issue #1176 , where the issue creator would like to see double clicking the widget title bars not pop open into sub-windows when they are in locked layout mode. This makes widgets no longer able to be popped out in locked layout mode. I'm not sure if this is intended behavior, but since the issue hadn't been closed yet, here's an attempt at fixing it.
> Double click no longer creates sub-windows in locked layout

- cola/models/prefs.py
- cola/widgets/prefs.py
Per our docs:
> The environment variable `$VISUAL` is consulted when no editor has been configured.
`$VISUAL` was only ever used as the default for the configuration parameter in the preferences UI, i.e. it was not consulted when invoking the editor (e.g. without ever going to the preferences). In that sense, the behavior arguably didn't match the doc. Change to consult it in both.
> prefs: consult $VISUAL on edit when gui.editor is not set, too

- cola/widgets/commitmsg.py
When the `cola.spellcheck` config item has not been previously set, simply starting up the app -- no need to actually do anything at all -- ends up writing its default value to the git config. This is mostly harmless, but also unnecessary clutter of the git config with defaults.
Fix by taking the built in default into account when checking if it should be written, not only the current configured value (which might be unset).
> fix(prefs): do not write `cola.spellcheck` config on start

- cola/app.py
kde for example still shows a window icon but on wayland, this only
works if the icon can be retrieved from the .desktop file. the name of
the .dektop file needs to be set from the application.
Signed-off-by: Martin Gysel <me@bearsh.org>
> enable window icon on wayland (on supported desktop environments)

- cola/i18n/ja.po
- Fix the display for "&Edit" and "&File", which are supposed to look like "編集(&E)" (displayed as "編集(E)", with the underline appearing   under E with Alt held).
- Fix a bizarre mistranslation of "<do stuff>..." to "<do stuff>中"
- Fix the Japanese names of Simplified Chinese and Traditional Chinese
- Use "未追跡" for "Untracked"
> i18n: Fix a small part of the Japanese translation

- docs/git-cola.rst
While reading the docs I noticed a few issues with the rendering. In particular:
* The `cola.terminalshellquote` defaults table renders not as a table, but as a long line of text.
* The CLI options are not quoted with double backticks and were subject to conversion to em-dashes.
While fixing these I also noticed a few typos and fixed those as well.
Please let me know if these rendering issues need to be fixed in another way.
> Fix documentation rendering errors

- cola/models/stash.py
- test/stash_model_test.py
If the branch name or message of a stash contained a slash then it was incorrectly displayed.
The maxsplit argument of str.split() is the maximum amount of splits that are done.
So you end up with at most maxsplit+1 elements.
We want to end up with at most 3 elements so it needs to be set to 2.
> stash: correctly show stashes containing slashes

- cola/models/main.py
- test/main_model_test.py
The crash is easily reproducible. Create a new repository and store a binary file in there. Then call the context menu of that file in git-cola.
```
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/cola/widgets/status.py", line 659, in contextMenuEvent
menu = self._create_context_menu()
File "/usr/lib/python3.10/site-packages/cola/widgets/status.py", line 678, in _create_context_menu
self._create_unstaged_context_menu(menu, s)
File "/usr/lib/python3.10/site-packages/cola/widgets/status.py", line 834, in _create_unstaged_context_menu
if self._model.stageable():
File "/usr/lib/python3.10/site-packages/cola/models/main.py", line 132, in stageable
return self.partially_stageable() or self.mode == self.modes_untracked
AttributeError: 'MainModel' object has no …
```
> Fix a crash on some context menu calls

- .github/workflows/main.yml
- .pylintrc
- cola/compat.py
- cola/core.py
- cola/fsmonitor.py
- cola/gitcfg.py
- cola/gravatar.py
- cola/qtutils.py
- cola/sequenceeditor.py
- cola/utils.py
- cola/version.py
- cola/widgets/commitmsg.py
- cola/widgets/createbranch.py
- cola/widgets/diff.py
- cola/widgets/gitignore.py
- cola/widgets/remote.py
- cola/widgets/startup.py
- cola/widgets/status.py
GitHub has updated ubuntu-latest to use Ubuntu 22.04. This release affects CI because some apt packages are no longer available for install, and a new pylint version is reporting additional lint warnings. However, while reviewing CI output, additional issues were identified and fixed.
This PR introduces these changes:
* Resolve `apt install` of packages that are renamed or unavailable on Ubuntu Jammy
* Resolve or disable pylint warnings that are showing up with newer pylint versions
* Re-enable and resolve several pylint warnings that were previously disabled
* Update GitHub Action versions to resolve multiple deprecation warnings
* Resolve pip deprecation warnings by installing wheel prior to installing Python dependencies
* Resolve severe CI artifact upload performance problems by …
> Fix GitHub Actions run failures

- docs/git-cola.rst
This converts an uppercase 5 (`%`) to a lowercase 5 (`5`). :wink:
> Fix a typo in `MD5`

- cola/widgets/startup.py
- test/startup_test.py
According to this issue, "[Cannot remove old folders from git-cola main window #1199](https://github.com/git-cola/git-cola/issues/1199)", I implemented context menu in prompt dialog (`git cola --prompt`).
The content of the context menu is same as favorite(and recent) widget (in `cola/widgets/bookmarks.py`) in main UI.
A lot of context menu functions come from the code.
- Open
- Open in New WIndow
- Open Using Default Application
- Copy
- Launch Editor
- Launch Terminal
- Clear Deafult Repository
- Rename Repository
- **only activated in "Folder" tab** [1]
- Delete from Bookmakrs List
- **only in `Favorites` view**
- Delete from Recent List
- **only in `Recent` view**
- Prune Missing Entries
> [1]
> In "List" tab, each item text is its repository's full path like …
> Add context menu in prompt dialog (git cola --prompt)

- cola/hotkeys.py
- cola/widgets/bookmarks.py
- cola/widgets/main.py
- cola/widgets/switcher.py
- test/switcher_test.py
Add repository name filtering component by [QSortFilterProxyModel](https://doc.qt.io/qtforpython/PySide6/QtCore/QSortFilterProxyModel.html). `Switcher` class in `cola/widgets/switcher.py` inherits it.
> NOTE
> - In this sentence, I use a word `moving key`. It means "selection move key like `UP`/`DOWN`".
> All moving keys is in `selection_move_keys` variable.
>
For versatility and make it reusable, impmlemented `Switcher` class to be able to be with it's list view or without it.
By passing candidate items which is or inherits `QStandardItemModel`, this can filter them by item name in it.
In this PR, I implemented to filter repositories. But, for example, if `QStandardItemModel` like "file" or "commit" passed, this can filter them.
I'll explain with-view/without-view class details below. …
> Add shortcut for filtering repositories in bookmarks widget and main widget

- cola/widgets/diff.py
Prior to this commit, the Unstage menu item in the `DiffEditor` context menu for a staged file would have an "add" icon ("+") even though the "Unstage Diff Hunk" menu item right below it has a "remove" icon ("-"). Update the code to dynamically switch the icon for the `.stage_or_unstage` menu item between "add" or "remove" depending on whether the file is modified or staged.
> Use "remove" icon for Unstage menu item

- .github/workflows/main.yml
- Makefile
- pytest.ini
- requirements/requirements-dev.txt
- setup.cfg
- test/helper.py
- tox.ini
Remove obsolete and unneeded packages from `tox.ini` and `requirements-dev.txt`.  Also drop `pylint-flake8` since it is essentially abandoned upstream, doesn't work with pytest>=7.0 (released February 2022) or flake8>=5.0 (released in July 2022) and instead simply invoke `flake8` directly.
> Clean up dev and tox requirements

- README.md
On a system where the Qt version is 5.13.2 "./env3/bin/pip install git-cola" installs PyQt in the version 5.15.9 (the latest). Subsequent "./env3/bin/git-cola" doesn't open the app window and causes following error to appear "No Qt bindings could be found". This patch fixes the issue by installing the PyQt version matching the Qt version on the system.
> Correct PyQt version that pip installs

- cola/models/dag.py
- cola/models/prefs.py
- cola/widgets/prefs.py
- docs/git-cola.rst
I've added the log date format pref discussed in #1312.
> prefs: add log date format to preferences for git-dag

- docs/git-dag.rst
like it was done in commit 85d7fdb by @kurtmckee for git-cola.rst
---
The double-hyphen at the [docs](https://git-cola.readthedocs.io/en/latest/git-dag.html#log-options)  or in the manpage `man git dag`  can easily mixed up with a single hyphen. At first I used a single hyphen and was confused about the error message I got.
> Prevent double-hyphen in git-dag doc

- cola/git.py
- test/git_test.py
- test/gitcfg_test.py
- test/gitcmds_test.py
- test/helper.py
This PR introduces the following:
* Fix a `GIT_CEILING_DIRECTORIES` parsing bug (Windows uses semicolons as a delimiter, not colons)
* Fix a bug in the `shutil.rmtree()` recovery function caused by an incorrect function comparison
* Resolve all path-related failures
* Resolves all newline-related failures
The design of the test suite currently uses `make` as the authoritative test runner; `tox` simply invokes `make`. This is incompatible with Windows platforms; `tox` needs to be the authoritative test runner which `make` invokes in order for tests to run cross-platform reliably. This redesign is not addressed in this PR.
Fixes #1331
> Fix tests on Windows

- cola/qtutils.py
On Windows, making a newly-created button visible causes a new window to open containing only the new button.
Testing shows that the buttons will be visible in whatever dock they are ultimately assigned to when the main git-cola window opens even if `.setVisible(True)` is not called first.
Therefore, the call to `.setVisible()` seems to be unnecessary.
Fixes #1329
> GUI: Stop making newly-created buttons immediately visible

- .pre-commit-config.yaml
pylint previously appeared to work in pre-commit _because I had a virtual environment activated_ with all dependencies installed.
Once the virtual environment was deactivated, the pylint pre-commit hook began failing just as it did in CI.
This makes the pylint pre-commit hook too untenable in CI _and_ in general local use, so this PR removes it entirely.
> Remove pylint as a pre-commit hook

- cola/widgets/prefs.py
Allow using smaller fonts. This can be useful for large HiDPI screens. For example, my Windows machine's screen's pixel density is 105 and the display scaling is set to 150% in 2160p. This makes the size of a 8 pt font too large. It can also vary depending on the Qt backend being used (DirectDraw vs xcb, etc.).
Perhaps there's some sense in lowering it even a bit further but that's enough changes for one day.
As usual, thank you for this wonderful software. The ability to edit diffs before reverting will surely come in handy.
> allow smaller font size for hidpi

- CONTRIBUTING.md
- cola/i18n/cs.po
- cola/i18n/es.po
- cola/i18n/fr.po
- test/i18n_test.py
changes were made based on [1343](https://github.com/git-cola/git-cola/pull/1343)
> remove translation of git jargon from Czech, Spanish and French

- .github/dependabot.yml
- .pre-commit-config.yaml
This PR introduces the following changes:
* Add a Dependabot configuration that will submit PRs to update GitHub action on a monthly basis (for example, a PR will be opened to update `actions/checkout@v3` to `v4` if this merges)
* Modify the pre-commit configuration to submit update PRs on a monthly basis (the default is weekly)
> Configure automatic updates

- cola/models/stash.py
- cola/widgets/remotemessage.py
pyupgrade identified two opportunities for Python 3.6+ syntax usage. I simply ran `pre-commit run -a` to address the issue.
This should resolve existing CI failures.
> Resolve pyupgrade pre-commit hook failures

- share/metainfo/git-cola.appdata.xml
- share/metainfo/git-dag.appdata.xml
https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#name-summary-and-developer-name is now mandatory so all the builds at https://github.com/flathub/com.github.git_cola.git-cola/pulls currently fail.
> Add AppStream developer name

- CHANGES.rst
- cola/resources.py
When Cola is installed directly into C:\Python3.12 on Windows
then the correct path to git-cola-sequence-editor was not being used.
Look in the same director as the current sprint when attempting to
find git-cola-sequence-editor. This makes cola rely less on the
physical structure of the install tree by checking for locations
relative to itself.
Closes: #1385
> resources: search for commands sibling to the running script

- cola/widgets/status.py
When merging patches, if you want to cache only a partial change for a file that has already been manually resolved on merge, in previous versions you had to stage the entire file, then find it among the other already staged files. With "Unstage" you can easily find the file in "Modified" then specifically stage just the line or hunk to be patched.
> widgets: add an "Unstage" option to the context menu for unmerged files

- CHANGES.rst
- cola/cmds.py
- cola/widgets/commitmsg.py
Allow users to override the commit date and time using a simple date widget. A slider is also provided for quickly setting the time backwards and forwards in time.
Suggested-by: Emily Vo <2014.evo@gmail.com>
> commitmsg: add a tool to set the commit time

- cola/widgets/main.py
- cola/widgets/standard.py
This is an untested monkey patch to possibly fix some crashes that occur when cola's current working directory gets deleted from underneath it.
I see this every now and then, and these two are the first ones that I managed to reproduce immediately when attempting to reproduce. They might not be the best ways to fix the issues (or fix them in the first place), but if nothing else, they flag where the crashes occurred for me.
> widgets: avoid some crashes when cwd is not found

- cola/models/main.py
The output of the `kreadconfig*` command regarding the kioslaverc/Proxy Settings/http(s)Proxy
configuration is in the following format:
```
HOST PORT
```
which is not the expected format of the value of the `proxy` variable:
```
HOST:PORT
```
Do a simple text replacement to fix it.
Fixes #1450.
Signed-off-by: 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
> main: fix incorrect proxy detection result in KDE

- cola/models/main.py
When the proxy is disabled globally in the System Settings in KDE the proxy host and address settings may still be preserved in the kioslaverc/Proxy Settings/*Proxy configuration settings.
Check the kioslaverc/Proxy Settings/httpProxy setting's value and return None when it is not set to "1"(meaning that the "Use manually specified proxy configuration" mode isn't selected).
Fixes #1452.
> main: fix incorrect proxy detection in KDE when proxy is disabled globally

- cola/i18n/ja.po
Fix incorrect use of progressive form in UI labels (e.g. “〜中”)
(Japanese) メニューの操作関連の命令形のラベルの翻訳が進行形(e.g. “〜中”)となっていたのを修正
---
Thanks for such a great tool!
> i18n/ja: Fix incorrect Japanese translation

- cola/cmds.py
[VSCode](https://code.visualstudio.com/docs/configure/command-line) and Cursor (fork of VSCode) use the following flag to open a file at a specific line number:
```
-g or --goto	When used with file:line{:character}, opens a file at a specific line and optional character position
```
I didn't test git-cola with these changes, I just tested I could open files ok as per the docs for those editors.
Only thing I'm not sure about, is the use of wildcards around the names of the editors. I did this to match how it was done for other editors. But I'm concerned this might match potentially other lesser well known editors, particularly any that would have "code" in their name. Can we drop the wildcards?
> Support VSCode and Cursor for opening at specific line number
