cola/cmds.py, cola/widgets/main.py
I usually press F5 a few times before I realize the correct key sequence is <kbd>Ctrl+R</kbd>.
=> main: Refresh with 'F5' in addition to 'Ctrl+R'

README.md
see https://groups.google.com/forum/#!topic/git-cola/9veoqPAQLWs
=> Clarify installation steps on Mac

share/doc/git-cola/Makefile
=> docs: Don't install .buildinfo or .gitignore

cola/app.py, cola/widgets/dag.py, cola/widgets/merge.py, contrib/win32/install.iss, po/de.po, po/es.po, po/fr.po, po/git-cola.pot, po/hu.po, po/id_ID.po, po/it.po, po/ja.po, po/pt_BR.po, po/ru.po, po/sv.po, po/zh_CN.po, po/zh_TW.po, share/doc/git-cola/relnotes/v1.4.1.2.rst, share/doc/git-cola/relnotes/v1.4.2.rst
=> Spelling fixes

po/glossary/zh_cn.po, po/zh_CN.po
updated zh_CN translation:
* added translation to new strings
* fixed fuzzy strings
Signed-off-by: ZH <zhanghan@gmx.cn>
=> po: update Chinese simplified translation

cola/widgets/status.py
Allow showing file(s) history from status view
=> status: add "View History" context menu action

po/es.po
It's not too much, but it's better than nothing :+1:
=> Completing most of missing translations (Spanish)

cola/cmds.py, cola/hotkeys.py, cola/models/prefs.py, cola/widgets/prefs.py, cola/widgets/status.py
Adds menu option "Blame..." to status items, defaults to "git gui blame <path>".
=> status: support blame GUI

cola/hotkeys.py
=> hotkeys: Remove duplicate OPEN

test/gitcfg_test.py
=> test: Fix gitcfg guitool_opts_mixed_case test

cola/fsmonitor.py
Instead of using `git.getcwd()` to get the Git worktree for monitoring for filesystem changes, use `git.worktree()`.  If that function returns `None`, the repository is bare.  In that case, simply skip monitoring the (non-existent) worktree.
=> Better filesystem monitoring for bare repositories

cola/models/main.py, cola/widgets/remote.py, share/doc/git-cola/relnotes/v2.8.rst
=> remote: add an option to configure the upstream branch when pushing

cola/compat.py, cola/widgets/standard.py, share/doc/git-cola/relnotes.rst
Simplify the fixes from #589 related to Python3 / PyQt5 compatibility.
=> Python3 PyQt5 compatibility tweaks

cola/widgets/browse.py, share/doc/git-cola/relnotes.rst
Correct the signal usage when expanding items.
=> Browse signals

cola/qtutils.py, cola/widgets/bookmarks.py
Implemented promptDouble that permits edit two edit box in same dialogue. Used for adding favourites and prompts favourites name and path.
Started with: #599
=> Unified prompt window adding favourites

Makefile, share/appdata/git-cola.appdata.xml, share/appdata/git-dag.appdata.xml
See https://people.freedesktop.org/~hughsient/appdata/ for more information.
=> Added AppData.xml files for Linux software gallery integration

generate-about
Unsure if the code change is appropriate, please review.
Signed-off-by: Ｖ字龍 <Vdragon.Taiwan@gmail.com>
=> generate-about: Let my email to be public

po/glossary/zh_tw.po, po/zh_TW.po
These changes are somewhat too critical to be pushed directly without someone noticing.
=> po: Chinese(Taiwan) translations: Replace several fundamental terms translations

README.md
Signed-off-by: Szymon Judasz szymon.judasz@student.uj.edu.pl
=> README: update year to 2017

po/fr.po
I've translated in french the software
=> French translation of project

cola/diffparse.py
It happens when git diffs file without newline at end of file
=> fix \\ No newline at end of file

po/uk.po
Signed-off-by: Igor Kopach <ikopach@ukr.net>
=> Add Ukrainian translation file

po/uk.po
Signed-off-by: Igor Kopach <ikopach@ukr.net>
=> Update ukrainian translation

COPYRIGHT, bin/git-cola, bin/git-dag, cola/app.py, cola/qtutils.py, cola/widgets/about.py, contrib/darwin/Info.plist, share/doc/git-cola/conf.py, share/git-cola/icons/README.md, share/git-cola/icons/dark/README.md
Change 2016 to 2017 in code comments
Signed-off-by: Szymon Judasz <szymon.judasz@student.uj.edu.pl>
=> doc: update year in copyright notes

cola/widgets/branch.py
Added 'Checkout as new branch' context menu action in remote branches
Signed-off-by: javierrodriguezcuevas <javierrodriguezcuevas@gmail.com>
=> branch: add context menu action

po/cs.po
Initial Czech translation. There are translated common strings in the
main window, the menu bar and drop-down menus (some strings still
untranslated).
Because git manuals are mainly in English, I let some key terms (e.g.
fetch, push, pull, merge) untranslated.
=> Czech translation

cola/cmds.py, cola/core.py, cola/gitcmds.py
There is another approach to solution of problem I previously touched in #745. What do you think about it?
=> RFC: Fixup non utf8 line staging

.gitignore, cola/widgets/imageview.py
Should use static brush or not?
See issue #788.
Same as Eye of GNOME, see eog-scroll-view.c.
Signed-off-by: xhl <xieofxie@gmail.com>
=> Draw checkboard for transparent image

cola/cmds.py, cola/widgets/dag.py, cola/widgets/filelist.py
The descriptions may need update
=> Dag updates

CONTRIBUTING.md, cola/fsmonitor.py, cola/gitcfg.py, cola/gitcmds.py, cola/utils.py, cola/widgets/completion.py, cola/widgets/standard.py
=> Spelling and grammar fixes

cola/cmds.py
=> DiffImage.unmerged_images: Fix candidate_merge_heads variable name

cola/widgets/remote.py
Signed-off-by: Pavel Rehak <pavel-rehak@email.cz>
=> fetch: add prune tooltip

po/cs.po
Signed-off-by: Pavel Rehak <pavel-rehak@email.cz>
=> po: update Czech translation

share/applications/git-cola.desktop
Signed-off-by: Pavel Rehak <pavel-rehak@email.cz>
=> git-cola.desktop: add cs Comment translation

po/es.po
more spanish translation to git-cola
=> improve and complete spanish translation (WIP)

po/ja.po
=> update translation in Japanese

po/zh_TW.po
"Force" is being used in both FETCH and PUSH operations, avoid translating it to "Force push".
Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>
=> po: Fix Chinese(Taiwan) Translation

cola/cmds.py
There's also the documentation to update, at https://git-cola.readthedocs.io/en/latest/git-cola.html#configure-your-editor
=> Goto line in sublime

.travis.yml
=> use travis apt installer

cola/cmds.py, cola/widgets/main.py, cola/widgets/status.py, cola/widgets/toolbar.py, cola/widgets/toolbarcmds.py
Add context menu, action menu and toolbar items that allows specific/all submodules update. Related-to #17.
=> Update git submodules support

cola/widgets/branch.py
=> Checkout branch when double clicked.

CONTRIBUTING.md
This piece of information was IMHO missing and would have
helped me a lot to start checking / improving translations.
Signed-off-by: Joachim Lusiardi <joachim@lusiardi.de>
=> Adds hint to regenerate the .mo file

po/pt_BR.po
Updates and fixes pt_BR translations
=> i18n: update pt_BR translations

README.md
Add reference to SlackBuilds.org for Slackware
=> README.md: add slackware instructions

po/hu.po
Glossary:
- repository: tároló
- branch: ág, elágazik
- remote: távoli
- upstream: távoli tároló
- origin: eredeti
- head: fej
- clone: klónozás
- checkout: átváltás ~~(SVN: lekérés)~~
- tracked: követett
- untracked: nem követett
- stage: kiszemelés ~~kiválasztás (=choose)~~
- unstage: elengedés ~~visszavonás (=revert)~~
- commit: véglegesítés, véglegesítő
- fetch: letöltés
- push: felküldés
- pull: lekérés
- merge: beolvasztás, egyesítés („ág beolvasztása, de beállítások egyesítése”)
- rebase: újraalapozás
- stash: félretevés, félretett változat
- diff: összehasonlítás
- reset: visszaállítás
- cherry-pick: kimazsolázás
- fixup : gyorsjavítás
- clear: tisztítás
- fast-forward: előrepörgetés, előrepörgetett
- blame: gyanúsító
=> Update Hungarian translation (100%)

share/git-cola/bin/ssh-askpass
tk might need to be added as an optional dependency too.
=> Fix shebang for ssh-askpass script

po/hu.po
I have reviewed the current translation, and fixed the issues. This commit was made in collaboration with @gyuris, the author of the previous pull request.
=> Update Hungarian localization

share/git-cola/bin/ssh-askpass
Simple check to omit the asterisks on username prompt #1004
=> Added check for the input box

share/appdata/git-dag.appdata.xml
Otherwise `appstream-util validate-relax --nonet` fails
=> Improve git-dag.appdata

share/git-cola/bin/ssh-askpass
Adds switch to hide (default) passphrase to SSH authentication dialog.
**v2**:
- use `else` in `if` block
=> Hide passphrase

po/pt_BR.po
=> Update pt_BR translations

README.md
We've been friends for ages but now it's time to tell the world.
Signed-off-by: Dave Cottlehuber <dch@skunkwerks.at>
=> docs: hello cola, meet FreeBSD

cola/widgets/diff.py
Changes in this Merge Request:-
Added code to enable word wrapping and made changes in UI (diff options).
=> Added word wrapping

cola/widgets/selectcommits.py
Changes in this Merge Request:-
1) Removed Close button.
2) Added Search functionality.
3) Moved input fields on top.
Can improve:- 
1) Can improve the search_list code by using set difference or using the same loop but it will make the code bit unreadable and won't reduce the theoretical time complexity of O(m + n) it may provide some efficiency though.
=> Added search functionality and fixed UI

README.md
Signed-off-by: Axel Heider <axelheider@gmx.de>
=> Updated readme section for Ubuntu packages

pynsist.cfg
I have added some unnecessary DLL files and folders to the exclude section of the pynsist file and also sorted them.
Related-to: #1094
=> pynsist: exclude unnecessary DLL files and folders

README.md
=> updated the wrong written word

CHANGES.rst
Good job on a new release! 🎉  Here's just a couple of amendments after reading the changes file.
- Correct link for toolbar icons
- Clarify "S" hotkey
=> Fix minor typos in v3.12.0 release notes

cola/widgets/dag.py
Prior to this change, if a commit was selected in the DAG window by clicking on a `Commit` item in the `GraphView`, two identical `diff.COMMITS_SELECTED` notifications would be sent, once from `Commit.itemChange()` for the previously selected `Commit` item, and again from `Commit.itemChange()` for the newly selected `Commit` item.
Fix by no longer sending the notification from `Commit.itemChange()`, but instead creating a new `GraphView.selection_changed()` method to send the notification and connecting it to the `scene.selectionChanged` signal.
=> Avoid duplicate diff.COMMITS_SELECTED notifications 

cola/diffparse.py, cola/widgets/diff.py, test/diffparse_test.py
Some cleanups, optimizations, and one bugfix to the diff line numbers code.
=> Diff line numbers work

share/metainfo/git-cola.appdata.xml
This is required for https://github.com/flathub/flathub/pull/3072
=> Add additional AppStream metadata

setup.cfg
required for https://github.com/flathub/com.github.git_cola.git-cola/pull/8.
=> Install the AppStream metadata file

cola/sequenceeditor.py
In the commit list view for the interactive rebase you can only select and modify a single entry. It becomes annoying really quickly needing to go one commit at a time when you, say, prepare a series of commits for a pull request and you want to squash multiple sets of commits or need to do final edits on multiple commit messages.
* use extended selection mode for RebaseTreeWidget, so that multiple commits can be selected holding Ctrl or Shift key
* add context action "Enable Selected" to enable selected commits
* add context action "Disable Selected" to disable selected commits
=> sequenceeditor: select, change, and shift multiple commits

.pylintrc, contrib/win32/cola
Get the pylint checks passing against pylint >= 2.7.0.
=> pylint compatibility

README.md
Hi,
i've added git-cola to the winget package database (https://github.com/microsoft/winget-pkgs/pull/109879). Maybe you want to add this note to the readme file on how it is installed.
=> Add winget installer to readme

cola/i18n/de.po
=> i18n: avoid translating Git jargon

cola/cmds.py, cola/gitcmds.py, cola/widgets/commitmsg.py
This PR should resolve issues caught by pylint and pre-commit.
If the tests against this PR pass, then the issues are resolved. 😀
=> Resolve causes of CI failures

cola/widgets/remote.py, share/metainfo/git-dag.appdata.xml
https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#name-summary-and-developer-name
=> Fix an AppStream validation error 

CHANGES.rst, cola/hotkeys.py, cola/widgets/commitmsg.py, cola/widgets/main.py, docs/hotkeys.html, docs/hotkeys_de.html, docs/hotkeys_zh_CN.html, docs/hotkeys_zh_TW.html
Closes: #1390
Reported-by: @mikeg-asi on github.com
=> hotkeys: use Alt-m for amend on macOS

cola/i18n/ja.po
This adds new Japaranse translation into ja.po only.
=> Update Japanese translation

.mailmap
I no longer prefer mixed-case mail addresses.
=> mailmap: fix Buo-ren Lin's mail address

cola/i18n/zh_TW.po, share/applications/git-dag.desktop
Added a few string translations I can confidently deal with.
=> i18n/zh_TW: update Chinese(Taiwan) translation
